### ISSUE TITLE
how to exit without losing shell?

### ISSUE THREAD

**Issue by f00d4w0rm4** [DominicBreuker/pspy#15]
I tried ctrl-c and ctrl-z but I lost my remote shell on both.

**Comment by gtjamesa** [comment]
Upgrade to an interactive shell before running so you can use Ctrl+C

**Comment by f00d4w0rm4** [comment]
Okay, thanks! I think I just had a partially interactive nc shell by using the "python import pty;..." command. I've seen people turn it to a fully interactive shell by setting the stty rows, columns, and term but I could never get that to work. I'll look into it some more though. Thanks again!
