### ISSUE TITLE
how i transfer pspy to the target machine?

### ISSUE THREAD

**Issue by guzzisec** [DominicBreuker/pspy#20]
sorry for this but how i transfer to the target machine? i tries with scp but nothing

scp: dest open "/pspy64": Permission denied
scp: failed to upload file pspy64 to

thanks!

**Comment by DominicBreuker** [comment]
hi guzzisec, 
how to transfer files is always different. in your case, scp sounds like a good choice. the reason it does not work seems to be that you lack write permissions at the destination path. if you copy to `/pspy64` and don't do so as root then you almost never have the permissions to do that. try other destinations like `/tmp/pspy64` and it should work. also don't forget to `chmod +x /tmp/pspy64` unless your executable bit is set already.
if this stuff makes no sense to you, read here: https://wiki.archlinux.org/title/File_permissions_and_attributes
