### ISSUE TITLE
Code of conduct is here

### ISSUE THREAD

**Issue by QuantumShadow87-cloud** [DominicBreuker/pspy#22]
EDIT by @DominicBreuker : link was made unclickable for safety reasons. download on your own risk if you want to find out whats inside that ZIP
this file was uploaded by @QuantumShadow87-cloud 

demo.zip https : / / github.com / DominicBreuker/pspy/files/11518310/demo.zip

**Comment by uunnxx** [comment]
Code of conduct in `.zip` format... suspicious

**Comment by DominicBreuker** [comment]
1st rule of the code of conduct: no posting of untrustworthy zip files

**Comment by QuantumShadow87-cloud** [comment]
> EDIT by @DominicBreuker : link was made unclickable for safety reasons. download on your own risk if you want to find out whats inside that ZIP this file was uploaded by @QuantumShadow87-cloud
> 
> demo.zip https : / / github.com / DominicBreuker/pspy/files/11518310/demo.zip

Said code was copied a used threw GitHub code source library thank you for your concern. If file didn’t open for you then you didn’t have the right system an software at the time to convert

**Comment by QuantumShadow87-cloud** [comment]
> EDIT by @DominicBreuker : link was made unclickable for safety reasons. download on your own risk if you want to find out whats inside that ZIP this file was uploaded by @QuantumShadow87-cloud
> 
> demo.zip https : / / github.com / DominicBreuker/pspy/files/11518310/demo.zip

An the file was just text talking about at the time my springbot application
